export const ActionTypes = {
    SET_BANNER: "SET_BANNER",
    SET_ROCKETS : "SET_ROCKETS",
    SEARCH_ROCKETS : "SEARCH_ROCKETS",
    SET_LOADING: "SET_LOADING",
    SET_CAPSULES: "SET_CAPSULES",
    SET_PAGE_NUMBER: "SET_PAGE_NUMBER",
    SET_SEARCH: "SET_SEARCH"
}